[markup]
  _merge = 'deep'
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 6
    ordered = false

[params]
  mainSections = ['posts']

[params.libraries]
[params.libraries.fontawesome]
  enable = true
  url = 'https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@6.2.0/css/all.min.css'
