baseURL = 'http://example.org/'
languageCode = 'zh-cn'
title = 'Hugo ICE Demo Site'
theme = 'github.com/megashow/hugo-ice'

[author]
  name = 'MegaShow'

[module]
[[module.imports]]
  path = 'github.com/megashow/hugo-ice'

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 6
    ordered = false

# 菜单
[menu]
[[menu.header]]
  name = '首页'
  url = '/'
  weight = 1
[[menu.header]]
  name = '归档'
  url = '/archives'
  weight = 2
# [[menu.header]]
#   name = '专题'
#   url = '/series'
#   weight = 3
[[menu.header]]
  name = '关于'
  url = '/about'
  weight = 100

[params]
  favicon = 'favicon.svg'
  startYear = 2022
  beian = ''
  mainSections = ['posts']

# 第三方依赖
[params.libraries]
# 第三方依赖 Font-Awesome，该依赖默认启用，如果禁用，主题部分功能将不能正常工作
# [params.libraries.fontawesome]
#   enable = true
#   url = <your-font-awesome-resource-url>

