baseURL = 'http://example.org/'
languageCode = 'zh-cn'
title = 'Hugo Ice Demo Site'
theme = 'hugo-ice'

hasCJKLanguage = true

[author]
  name = 'MegaShow'

[markup]
  [markup.highlight]
    lineNos = true
    style = 'manni'
    tabWidth = 4
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 6
    ordered = false

# 菜单
[menu]
[[menu.header]]
  name = '首页'
  url = '/'
  weight = 1
[[menu.header]]
  name = '归档'
  url = '/archives'
  weight = 2
[[menu.header]]
  name = '关于'
  url = '/about'
  weight = 100

[params]
  favicon = 'favicon.svg'
  startYear = 2022
  beian = ''
  mainSections = ['posts']
