baseURL = 'http://example.org/'
languageCode = 'zh-cn'
title = 'Hugo Ice Demo Site'
theme = 'hugo-ice'

disableKinds = ["RSS", "sitemap"]
hasCJKLanguage = true
copyright = "本站点所有文章除特别声明外，均采用 CC BY-NC-SA 4.0 许可协议，转载请注明出处！"

[markup]
  [markup.highlight]
    lineNos = true
    style = 'manni'
    tabWidth = 4
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 6
    ordered = false

# 菜单
[menu]
  [[menu.header]]
    name = '首页'
    url = '/'
    weight = 1
  [[menu.header]]
    name = '归档'
    url = '/archives'
    weight = 2
  [[menu.header]]
    name = '标签'
    url = '/tags'
    weight = 3
  [[menu.header]]
    name = '关于'
    url = '/about'
    weight = 100

# 主题参数
[params]
  mainSections = ['posts'] # 主 Sections 列表
  favicon = 'favicon.svg'  # 站点 Favicon 图标

  # 作者信息
  [params.author]
    name = 'MegaShow' # 作者昵称

  # 页脚
  [params.footer]
    since = 2022 # 站点成立时间
    beian = ''   # 备案信息
