baseURL = 'https://docs.icytown.com/hugo-ice'
languageCode = 'zh-CN'
title = 'Hugo Ice'
theme = 'hugo-ice'

disableKinds = ['rss', 'sitemap', 'taxonomy', 'term']
hasCJKLanguage = true

[markup]
  [markup.highlight]
    lineNos = true
    style = 'manni'
    tabWidth = 4
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 6
    ordered = false

[menu]
  [[menu.header]]
    name = '首页'
    url = '/'
    weight = 1
  [[menu.header]]
    name = '快速上手'
    url = '/getting-started/'
    weight = 2
  [[menu.header]]
    name = 'GitHub'
    url = 'https://github.com/megashow/hugo-ice'
    weight = 100

[params]
  mainSections = ['posts']
  [params.author]
    name = 'MegaShow'
  [params.footer]
    since = 2016
    beian = '粤ICP备17101777号-1'
